{
 "title": "Internet-2 Tech-24 Draft222222",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(source)" } },
   { "name": "Interface", "query": { "query": "label_values(interface_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Network Traffic Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(interface_statistics_in_octets[$__interval])",
     "legendFormat": "{{source}}:{{interface_name}}"
    },
    {
     "expr": "rate(gnmic_srl_if_stats_out_octets[$__rate_interval])",
     "legendFormat": "{{source}}:{{interface_name}}"
    },
    {
     "expr": "rate(gnmic_sros_if_stats_in_octets[$__rate_interval])",
     "legendFormat": "{{source}}::{{port_port_id}}"
    },
    {
     "expr": "rate(gnmic_sros_if_stats_out_octets[$__rate_interval])",
     "legendFormat": "{{source}}::{{port_port_id}}"
    }
   ]
  },
  {
   "title": "Network Topology",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "interface_traffic_rate_out_bps",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    },
    {
     "expr": "interface_traffic_rate_in_bps",
     "legendFormat": "{{source}}:{{interface_name}}:in"
    }
   ]
  },
  {
   "title": "$Node $Interface Traffic Throughput",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interface_traffic_rate_in_bps{source=\"$Node\", interface_name=\"$Interface\"}",
     "legendFormat": "{{source}}-{{interface_name}}-In"
    },
    {
     "expr": "interface_traffic_rate_out_bps{source=\"$Node\", interface_name=\"$Interface\"}",
     "legendFormat": "{{source}}-{{interface_name}}-out"
    }
   ]
  },
  {
   "title": "$Node Port Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interface_oper_state{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Node Interfaces Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(interface_statistics_in_octets{source=\"$Node\"}[$__rate_interval])"
    },
    {
     "expr": "rate(interface_statistics_out_octets{source=\"$Node\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "$Node CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "platform_control_cpu_total_instant{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Node  Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "platform_control_memory_utilization{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}